import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ReduxStoreProvider from "@/providers/ReduxStoreProvider";
import Navbar from "@/components/global/Navbar";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ReduxStoreProvider>
        <body className={inter.className}>
          <Navbar />
          <ToastContainer theme="colored" />
          {children}
        </body>
      </ReduxStoreProvider>
    </html>
  );
}
